Fix for WRFDA PGI compilation and 4DVAR runtime errors (#85)
TYPE: enhancement

KEYWORDS: WRFDA, PGI

SOURCE: internal

DESCRIPTION OF CHANGES:

1. Add -tp=px for crtm_2.2.3/libsrc/Sort_Utility.f90.
The original PGI compilation error without -tp=px:
pgf90 -c -O3 -w -Mfree -byteswapio Sort_Utility.f90
/tmp/pgf90W-bcqhLHTaDC.s: Assembler messages:
/tmp/pgf90W-bcqhLHTaDC.s:2356: Error: suffix or operands invalid for `vpcmpeqd'

2. Add da_ prefix for set_tiles to fix the following error when compiling for 4DVAR.
PGF90-S-0155-Ambiguous interfaces for generic procedure set_tiles (da_wrfvar_top.f: 3921)
PGF90-S-0155-Ambiguous interfaces for generic procedure set_tiles (da_wrfvar_top.f: 3921)
0 inform, 0 warnings, 2 severes, 0 fatal for da_solve_init

3. To fix 4DVAR runtime error with PGI, store intent(out) output in a temporary variable,
then assign it to the module variable that is accessed by different subroutines.
wrf: calling adjoint integrate
-------------- FATAL CALLED ---------------
FATAL CALLED FROM FILE: LINE: 1855
The microphysics option does not exist: mp_physics = 1075052544

LIST OF MODIFIED FILES:
M var/build/da_name_space.pl
M var/external/crtm_2.2.3/libsrc/makefile
M var/da/da_4dvar/da_4dvar.f90
M var/da/da_4dvar/da_4dvar_io.inc

TESTS CONDUCTED:
WRFDA regtests with intel_12.1.5 and gfortran_4.8.2 still ran fine after the changes made for pgi.